### ISSUE TITLE
Provide v11 / CAMT 54 File Import

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#142]
allow dragging a v11 file into an esr import and start processing it as if I had used the process "v11 importieren"
![image](https://cloud.githubusercontent.com/assets/16079655/23093086/c564f7d0-f5d9-11e6-8ac7-d3a5494c0ebe.png)

**Comment by metas-mk** [comment]
As first step I would suggest to not directly start the import. Instead press the corresponding process button after and initially setting the attachment as "file to to be processed". This way we don't mix it up with the default attachment functionality.

**Comment by metasnw** [comment]
yes, got your point. do you think we can still make it drag and drop cause its pretty cool?

**Comment by teosarca** [comment]
or... we can implement some hook mechanism which identifies that we are taking about "v11 import file" and asks the user if we wants to import it.

But this feature shall be ADDITIONAL to https://github.com/metasfresh/metasfresh-webui/issues/144

wdyt?

**Comment by teosarca** [comment]
update: introduced a new process which will allow to import from attachments.
![image](https://user-images.githubusercontent.com/1244701/30432279-d834a21e-9969-11e7-9c40-0919536082b0.png)

![image](https://user-images.githubusercontent.com/1244701/30432311-eb0bcf2a-9969-11e7-95d4-8de52da9787e.png)

**Comment by teosarca** [comment]
note to IT:
* test the new process (but before u have to upload the file)
* regression: make sure the old process is still working (swing only); also make sure the file was attached
* regression: briefly check process parameters in webui, if they are resolved, dropdowns are ok etc (reason: https://github.com/metasfresh/metasfresh-webui-api/commit/7430de40ba0241f88a78c4d246c68b6c1893cc38 )

**Comment by metas-rc** [comment]
Results of IT

* OK: The new process works well with cam54 files.
* OK: The new process works with v11 files.

NOK: In case of trying to import the same file again, I get " File not imported"error.  
Stacktrace provided in this pastebin: https://pastebin.com/8qJ3gNKU

NOK: After the lines are imported, I have to refresh the page in order to see them.

**Comment by metasnw** [comment]
hi @metas-rc 
please create follow ups for them.
this issue is fine as it already can be used.

**Comment by teosarca** [comment]
fixed NOK2.

**Comment by metas-rc** [comment]
Results of IT2: 
The NOK2 was not fixed yet. I created a followup for it: https://github.com/metasfresh/metasfresh-webui-api/issues/622
