### ISSUE TITLE
manufacturing order: create source HU is opening same view on right side as we have it on left side

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#665]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
![image](https://user-images.githubusercontent.com/1244701/32511351-36c50672-c3fc-11e7-94fe-772d9faa33a7.png)
![image](https://user-images.githubusercontent.com/1244701/32511362-3fa65f2a-c3fc-11e7-99e2-7bdf3e421719.png)
![image](https://user-images.githubusercontent.com/1244701/32511418-604b95ce-c3fc-11e7-9b13-138af7a83855.png)

### What is the expected or desired behavior?
the HUs view shall stay on right side.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* HU view remains on the right side after selecting a source HU: OK
* source HU appears on the left side, but is still shown in HU Editor on the right side, you have to close the HU Editor and open it again to see that the selected HU is not displayed in the editor anymore: i don't think that's ok
(at least i remember the HU Editor being updated correctly after selecting a source HU from previous tesitng)

**Comment by teosarca** [comment]
> source HU appears on the left side, but is still shown in HU Editor on the right side, you have to close the HU Editor and open it again to see that the selected HU is not displayed in the editor anymore: i don't think that's ok

agree, NOK

**Comment by teosarca** [comment]
fixed.
@metas-dh  pls check the same thing on picking too... might be that we have the same problem.
If that;s the case pls create an issue for it and link it to this one.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

I. manufacturing HU Editor:
* HU view remains on the right side after selecting a source HU: OK
*  source HU appears on the left side, but is still shown in HU Editor on the right side: not happening anymore, source HU only displayed on the left side: OK

II picking HU Editor:
after selecting a HU as source HU, the HU view on the right closes, but you don't get back to picking slots: => https://github.com/metasfresh/metasfresh-webui-frontend/issues/1341
