### ISSUE TITLE
HU taken out in Picking Tray Clearing still displayed in the Picking Slot in Picking Terminal

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#679]
### Is this a bug or feature request?
Bug
### What is the current behavior?
A HU taken out in Picking Tray Clearing is still displayed in the Picking Slot in Picking Terminal
#### Which are the steps to reproduce?
1. Pick a HU in Picking Terminal, & process the picking
2. Take out the HU in Picking Tray Clearing
3. Go back to Picking Terminal, check the Picking Slot you just cleared: HU is still displayed in the Slot, NOK
### What is the expected or desired behavior?
HU should not be displayed in the Picking Slot in Picking Terminal anymore, after it was taken out.

**Comment by teosarca** [comment]
you mean, you want that HU to vanish from the Picking terminal right away?
I suppose, if you would close the picking terminal and reopen it, the HU won't be there anymore, right?

**Comment by metas-dh** [comment]
> if you would close the picking terminal and reopen it, the HU won't be there anymore, right?

yes, it is still there; see HU 1000113 in the pics (taken just now): same HU displayed in picking terminal and as "taken out" in picking try clearing:

![2017-11-16 11_20_41-metasfresh](https://user-images.githubusercontent.com/18696715/32886270-7637eaa2-cac0-11e7-951c-3dbdd737c839.png)

![2017-11-16 11_21_08-metasfresh](https://user-images.githubusercontent.com/18696715/32886278-7ed084f8-cac0-11e7-8a84-881f8feb0a81.png)

**Comment by teosarca** [comment]
fixed by https://github.com/metasfresh/metasfresh-webui-api/issues/678

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

HU taken out in Picking Tray Clearing still displayed in the Picking Slot in Picking Terminal: 
=> still happening, HU only disappears from Picking Slot in Picking Terminal after shipment was created

**Comment by teosarca** [comment]
cannot reproduce:
![image](https://user-images.githubusercontent.com/1244701/32902765-f44a9aee-cafb-11e7-800f-1ce456eba33e.png)
![image](https://user-images.githubusercontent.com/1244701/32902785-02c6b18e-cafc-11e7-8b7e-0580e9ca4077.png)

**Comment by metas-dh** [comment]
update:
tested again, in mf15cloudit & w101:

sometimes works fine, sometimes does not

**Comment by metas-dh** [comment]
tested once more, in mf15 & w101: worked fine everytime
